name: CI Pipeline

on:
  push:

defaults:
  run:
    shell: powershell

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: fuction
        run: |
          function test {
              Write-Host -Object "123";    
          }

      - name: build
        run: |
          test;
