name: CI Pipeline

on:
  push:

env:
  test: ${{ github.workspace }}     

jobs:
  show-vars:
    runs-on: windows-latest
    steps:
      - name: Print all environment variables (PowerShell)
        shell: pwsh
        run: |
          Write-Host -Object $test;
