name: CI Pipeline
on:
  push:

jobs:
  show-vars:
    runs-on: windows-latest
    steps:
      - name: Print all environment variables (PowerShell)
        shell: pwsh
        run: |
          Get-ChildItem Env: | Sort-Object Name
