name: CI Pipeline

on:
  push:

env:
  DevOpsPath: '\\test01\DevOps'
  # GitLab 使用者資訊檔案路徑
  userInfoFilePath: '$DevOpsPath\GitLab-Userinfo.json'

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: build
        shell: pwsh
        run: |
          # 測試輸出
          $Env:userInfoFilePath 
