name: CI Pipeline

on:
  push:

env:
   slnFilePath: '${{ github.workspace }}\${{ github.event.repository.name }}.sln'

jobs:
  show-vars:
    runs-on: windows-latest
    steps:
      - name: Print all environment variables (PowerShell)
        shell: pwsh
        run: |
          Write-Host -Object $Env:slnFilePath;
