name: default

on:
  workflow_call:  # 可被其他 workflow 呼叫

defaults:
  run:
    shell: powershell

jobs:
  default:
    runs-on: windows-latest
    steps:
      - name: default
        run: |
          function New-Section {
            Write-Host -Object "123";
          }
