name: Default Template

on:
  workflow_call:  # 可被其他 workflow 呼叫

defaults:
  run:
    shell: powershell


jobs:
  default:
    runs-on: windows-latest
    steps:
      - name: Define and test function
        run: |
          function New-Section {
            Write-Host "123"
          }