name: Default Template

on:
  workflow_call:  # 讓它可以被呼叫

defaults:
  run:
    shell: pwsh

jobs:
  default:
    runs-on: windows-latest
    steps:
      - name: Define and test function
        run: |
          function New-Section {
            Write-Host "123"
          }